export * from './classes';

export * from './iconify';

export * from './register-icons';

// solar:pen-bold
// solar:bed-bold
// solar:eye-bold
// solar:copy-bold
// solar:flag-bold
// solar:list-bold
// solar:heart-bold
// solar:phone-bold
// solar:share-bold
// solar:inbox-bold
// solar:reply-bold
// solar:danger-bold
// solar:cart-3-bold
// solar:import-bold
// solar:export-bold
// solar:eraser-bold
// solar:user-id-bold
// solar:restart-bold
// solar:forward-bold
// solar:inbox-in-bold
// solar:download-bold
// solar:cup-star-bold
// solar:bell-off-bold
// solar:cart-plus-bold
// solar:bill-list-bold
// solar:bell-bing-bold
// solar:file-text-bold
// solar:user-plus-bold
// solar:eye-closed-bold
// solar:camera-add-bold
// solar:microphone-bold
// solar:add-circle-bold
// solar:play-circle-bold
// solar:info-circle-bold
// solar:medical-kit-bold
// solar:gallery-add-bold
// solar:dumbbell-large-minimalistic-bold
// solar:user-rounded-bold
// solar:close-circle-bold
// solar:check-circle-bold
// solar:wad-of-money-bold
// solar:shield-check-bold
// solar:clock-circle-bold
// solar:smartphone-2-bold
// solar:gallery-wide-bold
// solar:calendar-date-bold
// solar:verified-check-bold
// solar:trash-bin-trash-bold
// solar:danger-triangle-bold
// solar:forbidden-circle-bold
// solar:videocamera-record-bold
// solar:users-group-rounded-bold
// solar:printer-minimalistic-bold
// solar:stop-circle-bold
// solar:settings-bold
// solar:volume-bold
// solar:volume-loud-bold
// solar:monitor-bold
// solar:add-folder-bold
// solar:tv-bold
// solar:box-minimalistic-bold
// solar:video-frame-play-horizontal-bold
// solar:palette-bold
// solar:headphones-round-bold
// solar:like-bold
// solar:ssd-round-bold
// solar:tea-cup-bold
// solar:electric-refueling-bold
// solar:gamepad-bold
// solar:suitcase-tag-bold
// solar:case-minimalistic-bold
// solar:archive-down-minimlistic-bold
// solar:chat-round-dots-bold
// solar:letter-bold
// solar:letter-unread-bold
// solar:play-broken
// solar:multiple-forward-left-broken
// solar:dislike-outline
// solar:clock-circle-outline
// solar:chart-square-outline
// solar:hanger-2-outline
// solar:home-2-outline
// solar:letter-outline
// solar:figma-outline
// solar:like-outline
// solar:atom-outline
// solar:gallery-circle-outline
// solar:airbuds-case-open-outline
// solar:confetti-minimalistic-outline
// solar:quit-full-screen-square-outline
// solar:lock-password-outline
// solar:full-screen-square-outline
// solar:add-folder-outline
// solar:heart-outline
// solar:bill-list-bold-duotone
// solar:pallete-2-bold-duotone
// solar:bell-bing-bold-duotone
// solar:menu-dots-bold-duotone
// solar:home-angle-bold-duotone
// solar:settings-bold-duotone
// solar:notes-bold-duotone
// solar:inbox-in-bold-duotone
// solar:file-check-bold-duotone
// solar:file-corrupted-bold-duotone
// solar:file-bold-duotone
// solar:cloudy-moon-bold-duotone
// solar:align-right-bold-duotone
// solar:sort-by-time-bold-duotone
// solar:shield-keyhole-bold-duotone
// solar:tag-horizontal-bold-duotone
// solar:transfer-horizontal-bold-duotone
// solar:double-alt-arrow-up-bold-duotone
// solar:double-alt-arrow-down-bold-duotone
// solar:double-alt-arrow-right-bold-duotone
// solar:notebook-bold-duotone
// solar:palette-bold-duotone
// solar:atom-bold-duotone
// solar:users-group-rounded-bold-duotone
// solar:printer-minimalistic-bold-duotone
